{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.own.owntv",
    "module": "core",
    "version": "1.0.62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.62.aar",
          "url": "core-1.0.62.aar",
          "size": 8316256,
          "sha512": "7795c11fa58eaf39e989b893fccde1cc691927006f0fd1e8e7671a0e3133821f637c3bb02e244e17ee47ebcb4baab1f742d032208486b727022351e7dda21342",
          "sha256": "a6f230b4ac21d9ad1c3e3be094c758dfb3f91d4c3aff9e94c642a53c6fb80fa6",
          "sha1": "cbdb816822c4cd989b5548ceeb77b401fe1bf987",
          "md5": "7a32323080f36d9e0bcee6842d19ef35"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "androidx.tvprovider",
          "module": "tvprovider",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.github.albfernandez",
          "module": "juniversalchardet",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.2.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.62.aar",
          "url": "core-1.0.62.aar",
          "size": 8316256,
          "sha512": "7795c11fa58eaf39e989b893fccde1cc691927006f0fd1e8e7671a0e3133821f637c3bb02e244e17ee47ebcb4baab1f742d032208486b727022351e7dda21342",
          "sha256": "a6f230b4ac21d9ad1c3e3be094c758dfb3f91d4c3aff9e94c642a53c6fb80fa6",
          "sha1": "cbdb816822c4cd989b5548ceeb77b401fe1bf987",
          "md5": "7a32323080f36d9e0bcee6842d19ef35"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.62-sources.jar",
          "url": "core-1.0.62-sources.jar",
          "size": 989258,
          "sha512": "30077348b7dc0c7b359dc7504255f5d0fda2c9696e8d9f79b3a0073c4244797f5c1e3a05b738a8a0d32100282689bc22a2a127bbb39819af67d376f39a2104cb",
          "sha256": "3848d8bfad20cdc68be3cfefc9bc23645b5977175f15aff8030b572841897d8e",
          "sha1": "412f7e2a1fa8f4ae6d57f4cf3add2aeb4c6d9459",
          "md5": "e729037c8079394ba7ac7e91cf9e64b2"
        }
      ]
    }
  ]
}
