{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.own.owntv",
    "module": "core",
    "version": "1.0.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.64.aar",
          "url": "core-1.0.64.aar",
          "size": 8322992,
          "sha512": "acc97ae9637840df567489f7b0296fbbe3e93407bf6ae381525e6df387decabdb5b374d1f14fd58540b5a1c0ebf36c285e40294b892473a5d4ae3f853cd49904",
          "sha256": "d2482c946b424136e6928fdbcaa652a4cade2093b74afed685f3bad1461991fc",
          "sha1": "bf2ab5a1a1d7e1a60b16e6c1fcd6caf6b5e81487",
          "md5": "457dc9d28c4d2ca874a1d5a5af13ae4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "androidx.tvprovider",
          "module": "tvprovider",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.github.albfernandez",
          "module": "juniversalchardet",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.2.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.64.aar",
          "url": "core-1.0.64.aar",
          "size": 8322992,
          "sha512": "acc97ae9637840df567489f7b0296fbbe3e93407bf6ae381525e6df387decabdb5b374d1f14fd58540b5a1c0ebf36c285e40294b892473a5d4ae3f853cd49904",
          "sha256": "d2482c946b424136e6928fdbcaa652a4cade2093b74afed685f3bad1461991fc",
          "sha1": "bf2ab5a1a1d7e1a60b16e6c1fcd6caf6b5e81487",
          "md5": "457dc9d28c4d2ca874a1d5a5af13ae4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.64-sources.jar",
          "url": "core-1.0.64-sources.jar",
          "size": 989562,
          "sha512": "d48b22761882af4116308c8f7d76f878aaa3b2f275a964834ba59e0d947c0a895fe36fb93f5bb4782b0dabd799987319d7420576fd163528ff64b8b6ce0cab27",
          "sha256": "afde4aae2547b0cd0665d398b6f86097463c7252dbb2fc6be7a97f91989ce334",
          "sha1": "aa241865bd471913991ff7b0a7539703fcfd0209",
          "md5": "134629e34f455184685d489ede63f9ec"
        }
      ]
    }
  ]
}
